In [1]:
# pca

In [2]:
from sklearn import datasets
import numpy as np

In [4]:
iris = datasets.load_iris()
R = np.array(iris.data)

In [6]:
R.shape

(150, 4)

In [7]:
# numpy has an API to calculate a covariance matrix
# y-axes will be used for calculation
R_cov = np.cov(R, rowvar=False)

# print the covariance matrix
import pandas as pd
iris_covmat = pd.DataFrame(data=R_cov, columns=iris.feature_names)
iris_covmat.index = iris.feature_names
iris_covmat

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           0.685694         -0.042434           1.274315   
sepal width (cm)           -0.042434          0.189979          -0.329656   
petal length (cm)           1.274315         -0.329656           3.116278   
petal width (cm)            0.516271         -0.121639           1.295609   

                   petal width (cm)  
sepal length (cm)          0.516271  
sepal width (cm)          -0.121639  
petal length (cm)          1.295609  
petal width (cm)           0.581006

In [10]:
# calculate the eigenvalues and eigenvectors
eig_values, eig_vectors = np.linalg.eig(R_cov)

# print eig_value nad vector
print(eig_values)
print("...")
print(eig_vectors)


[4.22824171 0.24267075 0.0782095  0.02383509]
...
[[ 0.36138659 -0.65658877 -0.58202985  0.31548719]
 [-0.08452251 -0.73016143  0.59791083 -0.3197231 ]
 [ 0.85667061  0.17337266  0.07623608 -0.47983899]
 [ 0.3582892   0.07548102  0.54583143  0.75365743]]


In [12]:
featureVector = eig_vectors[:,:2]

In [13]:
featureVector

array([[ 0.36138659, -0.65658877],
       [-0.08452251, -0.73016143],
       [ 0.85667061,  0.17337266],
       [ 0.3582892 ,  0.07548102]])

In [14]:
featureVector_t = np.transpose(featureVector)

# R is the original iris dataset
R_t = np.transpose(R)

newDataset_t = np.matmul(featureVector_t, R_t)
newDataset = np.transpose(newDataset_t)

# check the shape of new reduced 2D dataset
newDataset.shape

(150, 2)